services:
  php:
    build:
      context: ./develop
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./develop/etc/nginx/global.conf:/etc/nginx/global/global.conf
      - ./develop/etc/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./develop/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./develop/etc/php/php-dev.ini:/etc/php7/php.ini
      - ./develop/etc/php/www-dev.conf:/etc/php7/php-fpm.d/www.conf
      - ./develop/log/:/var/log/
      - ./:/usr/share/nginx/html/
    working_dir: /usr/share/nginx/html/
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    environment:
      TZ: Asia/Taipei
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./develop/mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--init-connect="SET NAMES UTF8"', '--innodb-flush-log-at-trx-commit=0', '--default-time-zone=+08:00']
    ports:
      - "3306:3306"
networks:
  study: